//package com.example.hangout_hub
//
//<LinearLayout
//android:layout_width="match_parent"
//android:layout_height="wrap_content"
//android:layout_marginStart="16dp"
//android:layout_marginTop="16dp"
//android:layout_marginEnd="16dp"
//android:orientation="horizontal"
//android:paddingBottom="20dp"
//app:layout_constraintEnd_toEndOf="parent"
//app:layout_constraintStart_toStartOf="parent"
//app:layout_constraintTop_toBottomOf="@+id/textView9">
//
//<LinearLayout
//android:layout_width="match_parent"
//android:layout_height="match_parent"
//android:layout_weight="2"
//android:orientation="vertical">
//
//<androidx.cardview.widget.CardView
//android:layout_width="match_parent"
//android:layout_height="220dp"
//android:layout_marginLeft="10dp"
//android:layout_marginRight="10dp"
//android:visibility="visible"
//app:cardCornerRadius="20dp"
//app:cardElevation="20dp">
//
//<ImageView
//android:id="@+id/imageView8"
//android:layout_width="match_parent"
//android:layout_height="match_parent"
//android:scaleType="fitXY"
//app:srcCompat="@drawable/go_karting" />
//
//<LinearLayout
//android:layout_width="match_parent"
//android:layout_height="60dp"
//android:layout_gravity="bottom"
//android:orientation="horizontal">
//
//<TextView
//android:id="@+id/textView12"
//android:layout_width="wrap_content"
//android:layout_height="wrap_content"
//android:layout_gravity="center"
//android:layout_weight="1"
//android:gravity="center"
//android:text="Go-karting"
//android:textColor="@color/white"
//android:textSize="20sp" />
//
//<Button
//android:id="@+id/btnmapkarting"
//android:layout_width="35dp"
//android:layout_height="wrap_content"
//android:layout_weight="1"
//android:background="@drawable/uilogin"
//android:text="Map"
//android:textSize="18sp" />
//</LinearLayout>
//
//<androidx.cardview.widget.CardView
//android:layout_width="48dp"
//android:layout_height="48dp"
//android:layout_gravity="right"
//android:layout_margin="10dp"
//app:cardCornerRadius="48dp">
//
//<ImageView
//android:id="@+id/imageView22"
//android:layout_width="32dp"
//android:layout_height="32dp"
//android:layout_gravity="center"
//app:srcCompat="@drawable/baseline_star_rate_24" />
//</androidx.cardview.widget.CardView>
//</androidx.cardview.widget.CardView>
//
//<androidx.cardview.widget.CardView
//android:layout_width="match_parent"
//android:layout_height="220dp"
//android:layout_marginLeft="10dp"
//android:layout_marginTop="20dp"
//android:layout_marginRight="10dp"
//app:cardCornerRadius="20dp"
//app:cardElevation="20dp">
//
//<ImageView
//android:id="@+id/imageView17"
//android:layout_width="match_parent"
//android:layout_height="match_parent"
//android:scaleType="fitXY"
//app:srcCompat="@drawable/turf" />
//
//<LinearLayout
//android:layout_width="match_parent"
//android:layout_height="60dp"
//android:layout_gravity="bottom"
//android:orientation="horizontal">
//
//<TextView
//android:id="@+id/textView23"
//android:layout_width="wrap_content"
//android:layout_height="wrap_content"
//android:layout_gravity="center"
//android:layout_weight="1"
//android:gravity="center"
//android:text="Turf"
//android:textColor="@color/white"
//android:textSize="20sp" />
//
//<Button
//android:id="@+id/btnmapturf"
//android:layout_width="35dp"
//android:layout_height="wrap_content"
//android:layout_weight="1"
//android:background="@drawable/uilogin"
//android:text="Map"
//android:textSize="18sp" />
//
//</LinearLayout>
//
//<androidx.cardview.widget.CardView
//android:layout_width="48dp"
//android:layout_height="48dp"
//android:layout_gravity="right"
//android:layout_margin="10dp"
//app:cardCornerRadius="48dp">
//
//<ImageView
//android:id="@+id/imageView24"
//android:layout_width="32dp"
//android:layout_height="32dp"
//android:layout_gravity="center"
//app:srcCompat="@drawable/baseline_star_rate_24" />
//</androidx.cardview.widget.CardView>
//
//</androidx.cardview.widget.CardView>
//
//<androidx.cardview.widget.CardView
//android:layout_width="match_parent"
//android:layout_height="220dp"
//android:layout_marginLeft="10dp"
//android:layout_marginTop="20dp"
//android:layout_marginRight="10dp"
//app:cardCornerRadius="20dp"
//app:cardElevation="20dp">
//
//<ImageView
//android:id="@+id/imageView11"
//android:layout_width="match_parent"
//android:layout_height="match_parent"
//android:scaleType="fitXY"
//app:srcCompat="@drawable/girraffe_park" />
//
//<LinearLayout
//android:layout_width="match_parent"
//android:layout_height="60dp"
//android:layout_gravity="bottom"
//android:orientation="horizontal">
//
//<TextView
//android:id="@+id/textView25"
//android:layout_width="wrap_content"
//android:layout_height="wrap_content"
//android:layout_gravity="center"
//android:layout_weight="1"
//android:gravity="center"
//android:text="Girraffe"
//android:textColor="@color/white"
//android:textSize="20sp" />
//
//<Button
//android:id="@+id/btnmapgirraffe"
//android:layout_width="35dp"
//android:layout_height="wrap_content"
//android:layout_weight="1"
//android:background="@drawable/uilogin"
//android:text="Map"
//android:textSize="18sp" />
//
//</LinearLayout>
//
//<androidx.cardview.widget.CardView
//android:layout_width="48dp"
//android:layout_height="48dp"
//android:layout_gravity="right"
//android:layout_margin="10dp"
//app:cardCornerRadius="48dp">
//
//<ImageView
//android:id="@+id/imageView26"
//android:layout_width="32dp"
//android:layout_height="32dp"
//android:layout_gravity="center"
//app:srcCompat="@drawable/baseline_star_rate_24" />
//</androidx.cardview.widget.CardView>
//</androidx.cardview.widget.CardView>
//</LinearLayout>
//
//<LinearLayout
//android:layout_width="match_parent"
//android:layout_height="match_parent"
//android:layout_weight="2"
//android:orientation="vertical">
//
//<androidx.cardview.widget.CardView
//android:layout_width="match_parent"
//android:layout_height="220dp"
//android:layout_marginLeft="10dp"
//android:layout_marginRight="10dp"
//app:cardCornerRadius="20dp"
//app:cardElevation="20dp">
//
//<ImageView
//android:id="@+id/imageView12"
//android:layout_width="match_parent"
//android:layout_height="match_parent"
//android:scaleType="fitXY"
//app:srcCompat="@drawable/paintball" />
//
//<LinearLayout
//android:layout_width="match_parent"
//android:layout_height="60dp"
//android:layout_gravity="bottom"
//android:orientation="horizontal">
//
//<TextView
//android:id="@+id/textView27"
//android:layout_width="wrap_content"
//android:layout_height="wrap_content"
//android:layout_gravity="center"
//android:layout_weight="1"
//android:gravity="center"
//android:text="Paintball"
//android:textColor="@color/white"
//android:textSize="20sp" />
//
//<Button
//android:id="@+id/btnmappaintball"
//android:layout_width="35dp"
//android:layout_height="wrap_content"
//android:layout_weight="1"
//android:background="@drawable/uilogin"
//android:text="Map"
//android:textSize="18sp" />
//
//</LinearLayout>
//
//<androidx.cardview.widget.CardView
//android:layout_width="48dp"
//android:layout_height="48dp"
//android:layout_gravity="right"
//android:layout_margin="10dp"
//app:cardCornerRadius="48dp">
//
//<ImageView
//android:id="@+id/imageView28"
//android:layout_width="32dp"
//android:layout_height="32dp"
//android:layout_gravity="center"
//app:srcCompat="@drawable/baseline_star_rate_24" />
//</androidx.cardview.widget.CardView>
//</androidx.cardview.widget.CardView>
//
//<androidx.cardview.widget.CardView
//android:layout_width="match_parent"
//android:layout_height="220dp"
//android:layout_marginLeft="10dp"
//android:layout_marginTop="20dp"
//android:layout_marginRight="10dp"
//app:cardCornerRadius="20dp"
//app:cardElevation="20dp">
//
//<ImageView
//android:id="@+id/imageView13"
//android:layout_width="match_parent"
//android:layout_height="match_parent"
//android:scaleType="fitXY"
//app:srcCompat="@drawable/pins" />
//
//<LinearLayout
//android:layout_width="match_parent"
//android:layout_height="60dp"
//android:layout_gravity="bottom"
//android:orientation="horizontal">
//
//<TextView
//android:id="@+id/textView29"
//android:layout_width="wrap_content"
//android:layout_height="wrap_content"
//android:layout_gravity="center"
//android:layout_weight="1"
//android:gravity="center"
//android:text="Pins"
//android:textColor="@color/white"
//android:textSize="20sp" />
//
//<Button
//android:id="@+id/btnmappins"
//android:layout_width="35dp"
//android:layout_height="wrap_content"
//android:layout_weight="1"
//android:background="@drawable/uilogin"
//android:text="Map"
//android:textSize="18sp" />
//
//</LinearLayout>
//
//<androidx.cardview.widget.CardView
//android:layout_width="48dp"
//android:layout_height="48dp"
//android:layout_gravity="right"
//android:layout_margin="10dp"
//app:cardCornerRadius="48dp">
//
//<ImageView
//android:id="@+id/imageView30"
//android:layout_width="32dp"
//android:layout_height="32dp"
//android:layout_gravity="center"
//app:srcCompat="@drawable/baseline_star_rate_24" />
//</androidx.cardview.widget.CardView>
//</androidx.cardview.widget.CardView>
//
//<androidx.cardview.widget.CardView
//android:layout_width="match_parent"
//android:layout_height="220dp"
//android:layout_marginLeft="10dp"
//android:layout_marginTop="20dp"
//android:layout_marginRight="10dp"
//app:cardCornerRadius="20dp"
//app:cardElevation="20dp">
//
//<ImageView
//android:id="@+id/imageView15"
//android:layout_width="match_parent"
//android:layout_height="match_parent"
//android:scaleType="fitXY"
//app:srcCompat="@drawable/cjs" />
//
//<LinearLayout
//android:layout_width="match_parent"
//android:layout_height="60dp"
//android:layout_gravity="bottom"
//android:orientation="horizontal">
//
//<TextView
//android:id="@+id/textView10"
//android:layout_width="wrap_content"
//android:layout_height="wrap_content"
//android:layout_gravity="center"
//android:layout_weight="1"
//android:gravity="center"
//android:text="Cj's"
//android:textColor="@color/white"
//android:textSize="20sp" />
//
//<Button
//android:id="@+id/btnmapcjs"
//android:layout_width="35dp"
//android:layout_height="wrap_content"
//android:layout_weight="1"
//android:background="@drawable/uilogin"
//android:text="Map"
//android:textSize="18sp" />
//
//</LinearLayout>
//
//<androidx.cardview.widget.CardView
//android:layout_width="48dp"
//android:layout_height="48dp"
//android:layout_gravity="right"
//android:layout_margin="10dp"
//app:cardCornerRadius="48dp">
//
//<ImageView
//android:id="@+id/imageView9"
//android:layout_width="32dp"
//android:layout_height="32dp"
//android:layout_gravity="center"
//app:srcCompat="@drawable/baseline_star_rate_24" />
//</androidx.cardview.widget.CardView>
//</androidx.cardview.widget.CardView>
//</LinearLayout>
//</LinearLayout>